name: Cargo Build & Test

on: [push, pull_request]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: ktt-shopsystem
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [i386, amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./.github/actions/container-build ${{ matrix.architecture }}
