name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: ktt-shopsystem
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Ubuntu Bug Workaround
        run: sudo apt install libunwind-dev
      - name: Install required system libraries
        run: sudo apt install libcairo2-dev libpango1.0-dev libgpgme-dev libarchive-dev libgstreamer1.0-dev pkg-config
      - name: Prepare Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Build Debian Package
        run: cargo deb
